# Generated by Django 2.1.5 on 2021-09-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='remarks',
            field=models.CharField(choices=[('Epic', 'Epic'), ('Good', 'Good'), ('Fine', 'Fine'), ('Bad', 'Bad'), ('Pathetic', 'Pathetic')], default='Good', max_length=20),
        ),
    ]
