# Generated by Django 2.1.5 on 2021-09-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='remarks',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
