# Generated by Django 2.1.5 on 2021-09-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('name', models.CharField(max_length=100, null=True)),
                ('message', models.TextField(max_length=250)),
                ('remarks', models.CharField(choices=[('Epic', 'Epic'), ('Good', 'Good'), ('Fine', 'Fine'), ('Bad', 'Bad'), ('Pathetic', 'Pathetic')], default='Good', max_length=40)),
            ],
        ),
    ]
