# Generated by Django 2.1.5 on 2021-09-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remarks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('name', models.CharField(max_length=100, null=True)),
                ('message', models.TextField(max_length=250)),
                ('remarks', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
