# Generated by Django 2.1.5 on 2021-09-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
