# Generated by Django 2.1.5 on 2021-09-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0002_auto_20210911_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='price',
            field=models.FloatField(default=100.55, null=True),
        ),
    ]
