# Generated by Django 2.1.5 on 2021-09-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0003_auto_20210911_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
