# Generated by Django 2.1.5 on 2021-09-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0004_auto_20210911_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/uploads'),
        ),
    ]
