# Generated by Django 2.1.5 on 2021-09-11 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0006_auto_20210911_2220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Automobile',
        ),
    ]
